### ISSUE TITLE
build fails on Fedora 28

### ISSUE THREAD

**Issue by beroset** [epri-dev/IEEE-2030.5-Client#1]
A number of things cause the `build.sh` file to fail to build on Fedora 28.  First, the gcc-x86_64-linux-gnu package (see https://www.rpmfind.net/linux/RPM/fedora/updates/testing/28/x86_64/Packages/g/gcc-x86_64-linux-gnu-8.1.1-3.fc28.x86_64.html) does not support building user-space programs, only the kernel.
Maybe CMake, autotools or a conventional Makefile could be used instead.

**Comment by markslicker** [comment]
Hello, does the attached script work for you?

[build.sh.zip](https://github.com/epri-dev/IEEE-2030.5-Client/files/2215184/build.sh.zip)

This will compile with plain gcc, no target prefix.

**Comment by beroset** [comment]
Yes, that works just fine.  I know that the target is currently only Linux, but if it's ever desired later to port to Mac or Windows, maybe the `if` clause could be this:

    if [[ $system == "linux" && -n "${!host}" ]]; then

And the rest of the code from that point to the end could stay as it originally was.  I'll leave it to you to decide which you like better.  Both ways work on my system.
